name: CI
on: [push, pull_request]

jobs:
  one:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Create Issue on GitHub Repos pull ppppp
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data '{ "title": "Automated issue for commit: ...", \
          "body":"This was created by workflow and commit was: _${{ github.sha}}_.", \
          "assignees": ["${{github.event.pull_request.user.login }}"] }'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: slack message with issue
        #if: failure() == 'false'
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Hello there was issue! - has sent from Milos GitHub actions CI"}' \
          ${{ secrets.SLACK_WEBHOOK }}