name: CI
on: [push, pull_request]

jobs:
  one:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: slack message with issue
        if: failure() == 'false'
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Hello there was issue! - has sent from Milos GitHub actions CI"}' \
          ${{ secrets.SLACK_WEBHOOK }}