name: Container
on: [push]


jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
  mule-docker-teo:
    runs-on: ubuntu-latest
    container:
      image: mhantl/mule-ce-poc:3.8.1
      credentials:
        username: ${{ secrets.DOCKER_USER }}
#        password: ${{ secrets.DOCKER_USER_PASSWORD }}
        password: ${{ secrets.DOCKER_ACCESS_RWD_TOKEN }}
    steps:
      - name: Log Mule RT and Java version
        run: |
          ls -la /opt/mule
          java -version
  mule-docker-tnz:
    runs-on: ubuntu-latest
    container:
      image: mhantl/mule-ce-poc:3.9.0
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_USER_PASSWORD }}
    steps:
      - name: Log Mule RT and Java version
        run: |
          ls -la /opt/mule
          java -version          